# ./8/traefik.yml
  traefik:
    image: index.docker.io/library/traefik:latest
    container_name: traefik
    restart: unless-stopped
    volumes:
      - ./certs:/letsencrypt
    command:
      # For the Dashboard, uncomment this...good for debugging
      # - --api.insecure=true
      # Comment this if you don't want to record HTTP access logs
      - --accesslog=true
      - --providers.docker=true
      # Note the Docker Socket Proxy that was setup in the previous step.
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.dnschallenge=true
      # Change this to your DNS provider
      - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      # This will come in handy if you've got an internal DNS resolver, switch to your preferred external resolver.
      - --certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53
      # Put emails and other sensitive data in your .env
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      # Set to staging to validate you can issue a certificate successfully.
      # Switch the URL to https://acme-v02.api.letsencrypt.org/directory when you are ready.
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    env_file: .env
    ports:
      - 443:443
      - 80:80
      # For the Dashboard, uncomment this as well
      # - 8080:8080
    dns:
      - 1.1.1.1
    # Because Home Assistant is running on host networking, tell
    # Traefik, to look at the gateway/host.
    extra_hosts:
      - host.docker.internal:172.18.0.1